{% set version = "2025.03.0" %}
{% set python_min = "3.10" %}

package:
  name: "pyflextrkr"
  version: "{{ version }}"

source:
  url: https://github.com/FlexTRKR/PyFLEXTRKR/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 64c84bfc218f19e78f72754a3675662d44e73e1e42a9b49d58f337cb9a433cc4

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=2.0
    - matplotlib-base >=3
    - xarray >=0.14
    - pandas >=0.25
    - scipy >=1.4
    - netcdf4 >=1.5
    - pytz >=2019
    - cartopy >=0.17
    - dask >=2.9
    - scikit-image >=0.22
    - joblib >=0.14
    - ipython >=7.0
    - PyYAML >=5.4
    - astropy-base
    - colorcet
    - colormath
    - seaborn
    - scikit-learn
    - ffmpeg
    - xesmf >=0.8

test:
  requires:
    - python {{ python_min }}
    - pyflextrkr
  imports:
    - pyflextrkr

about:
  home: https://github.com/FlexTRKR/PyFLEXTRKR
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: "A Python package for atmospheric feature tracking."
  description: |
    PyFLEXTRKR is a Python package for tracking atmospheric features such as clouds and storms.
  doc_url: https://github.com/FlexTRKR/PyFLEXTRKR
  dev_url: https://github.com/FlexTRKR/PyFLEXTRKR

extra:
  recipe-maintainers:
    - feng045
